### ISSUE TITLE
中间标题栏的位置不对

### ISSUE THREAD

**Issue by fingerplay** [spicyShrimp/iOS-11-UINavigationItem-SXFixSpace#1]
把左右barbutton的约束移除后，中间的titleview的约束不对了，导致显示不出来或者撑开到整个屏幕的宽度

**Comment by spicyShrimp** [comment]
我这边观察了约束条件,重新修改了下移除的约束条件,之前判断的是错误的,导致约束冲突的是这一条约束"<NSLayoutConstraint:0x60400009c480 UILayoutGuide:0x6040001a09a0'BackButtonGuide(0x7f9314722de0)'.trailing >= _UINavigationBarContentView:0x7f9314709cc0'2'.leading + 20   (active)>",

其会与新增的约束 [view.superview addConstraint:[NSLayoutConstraint constraintWithItem:view
                                                                           attribute:NSLayoutAttributeLeading
                                                                           relatedBy:NSLayoutRelationEqual
                                                                              toItem:view.superview
                                                                           attribute:NSLayoutAttributeLeading
                                                                          multiplier:1.0
                                                                            constant:0]];
产生冲突,

之前的判断有误,现在已经修正了,如果还有问题,你可以尝试遍历所有的约束,找到影响你的布局的约束,进行修改或者删除(我自己测试下来是没有问题的)
