### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by suzhiqiu** [spicyShrimp/iOS-11-UINavigationItem-SXFixSpace#2]
再push一个viewcontronller。回来的时候。  靠左边的约束直接没有了。返回按钮直接靠到屏幕去了，没有间距。      如果不push，用起来是正常的。  有联系方式么？

**Comment by spicyShrimp** [comment]
写在viewWillAppear:中,保证在界面将要显示的时候确保其约束即可
类似demo中的
-(void)viewWillAppear:(BOOL)animated{
    [super viewWillAppear:animated];
    [self configBarItem];
}

-(void)configBarItem{
    if (self.navigationController.viewControllers.count > 0) {
        self.navigationItem.rightBarButtonItem = [UIBarButtonItem itemWithTarget:self action:@selector(pushAction) image:[UIImage imageNamed:@"nav_add"]];
    }
    if (self.navigationController.viewControllers.count > 1) {
        self.navigationItem.leftBarButtonItem = [UIBarButtonItem itemWithTarget:self action:@selector(popAction) image:[UIImage imageNamed:@"nav_back"]];
    }
}

**Comment by spicyShrimp** [comment]
我的邮箱地址78268731@qq.com  如果需要添加请备注

**Comment by spicyShrimp** [comment]
我的QQ 78268731  如果需要添加请备注,谢谢
