### ISSUE TITLE
自定义返回按钮 系统自动多了个返回按钮 这个什么原因啊

### ISSUE THREAD

**Issue by fengBernard** [spicyShrimp/iOS-11-UINavigationItem-SXFixSpace#4]

**Comment by spicyShrimp** [comment]
具体情况能再描述一下吗?

**Comment by fengBernard** [comment]
http://www.cocoachina.com/bbs/read.php?tid=1725706 类似这个

**Comment by spicyShrimp** [comment]
你是使用了backButton? 这个分类没有排除backButton  你使用leftButton代替backButton应该就没有问题了

**Comment by fengBernard** [comment]
left、是没有问题的 恩 我也发现 自定义back 系统会自动复制一个

**Comment by spicyShrimp** [comment]
嗯嗯   一般我们都是不会使用backButton的

**Comment by fengBernard** [comment]
。。恩  我也是想探讨为啥

**Comment by spicyShrimp** [comment]
因为系统的backButton 跟leftButton在界面上的布局是不一样的
@property(nonatomic,assign) BOOL hidesBackButton __TVOS_PROHIBITED; // If YES, this navigation item will hide the back button when it's on top of the stack.
说明的很清楚  其会讲backButton放在最外层  我没有遍历修改其约束的话 它肯定是默认的状态
所以backbutton和leftButton重叠

**Comment by fengBernard** [comment]
是的 是不一样的
