### ISSUE TITLE
你的这个我放在一个文件夹内就运行出错

### ISSUE THREAD

**Issue by IPOSDai** [spicyShrimp/iOS-11-UINavigationItem-SXFixSpace#5]
在执行的时候没法找到    Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[UIBarButtonItem itemWithTarget:action:image:]: unrecognized selector sent to class 0x104e51c20'

**Comment by spicyShrimp** [comment]
你使用的时候添加头文件了吗?

**Comment by IPOSDai** [comment]
添加了。就使用你的demo，把相关文件放到一个文件夹中，再把这个文件夹已group放到项目中，都出现这种问题

**Comment by spicyShrimp** [comment]
你给我发一个你的demo吧 我看看你到底是怎么整的,别人使用都是没有问题的  我的邮箱78268731@qq.com

**Comment by IPOSDai** [comment]
就是你的项目，我把它们通通放到一个文件夹，在iOS 11 上模拟器就出错。 我给你一个你的Demo放在文件夹的。

**Comment by spicyShrimp** [comment]
找到问题的原因了
这个不是代码的问题
Xcode 运行报错unrecognized selector sent to class的话
是因为XCode没有找到实现的方法
这个是XCode自身的问题导致的
一般的解决方法是设置targets的building setting 的Other Linker flag  
添加以下两项
-all_load 
-ObjC

如果还是不行的话,就把你需要添加的文件直接拖到该项中,手动关联即可
你之前的问题,就是因为这个引起的,只要在Other Linker flag  添加需要相应的文件路径即可
<img width="849" alt="default" src="https://user-images.githubusercontent.com/13727969/30782640-6b3afe2c-a168-11e7-8857-bdc5f0964913.png">

**Comment by IPOSDai** [comment]
OK，居然还要这个。谢谢！

**Comment by spicyShrimp** [comment]
这个不是项目本身的原因  应该是xcode对swift添加了命名空间和OC本身没有命名空间有关系,这个是个人的看法,对于这个问题貌似只能手动添加引用来解决

**Comment by spicyShrimp** [comment]
对于不会手写link flags的话 
还有另外的一种方案
<img width="1400" alt="wx20170925-144933 2x" src="https://user-images.githubusercontent.com/13727969/30795734-83ea2b34-a201-11e7-8af2-6998590dcb4f.png">
就是勾选target即可
目前看来,这个确实是xcode的一个bug

**Comment by YanPengImp** [comment]
如果要在导航栏右边设置多个按钮，ios11上面使用rightBarButtonItems这个无效，不知道什么原因

**Comment by spicyShrimp** [comment]
rightBarButtonItems方法我没有写,  我这边的建议是使用一个父视图当做customView 上面添加两个按钮, 然后使用这个的视图创建一个item

**Comment by spicyShrimp** [comment]
如果问题解决请关闭issues

**Comment by YanPengImp** [comment]
是因为设置leftBarButtonItem的时候用自定义视图里面有个去掉右边约束，所有就导致设置rightBarButtonItems的时候出现在了屏幕之外。
