### ISSUE TITLE
可以放两个按钮吗

### ISSUE THREAD

**Issue by JerryDJX** [spicyShrimp/iOS-11-UINavigationItem-SXFixSpace#6]
如何同时放两个按钮呢？
`        UIBarButtonItem *item1 = [UIBarButtonItem itemWithTarget:self action:@selector(pushAction) image:[UIImage imageNamed:@"nav_add"]];
        UIBarButtonItem *item2 = [UIBarButtonItem itemWithTarget:self action:@selector(pushAction) image:[UIImage imageNamed:@"nav_add"]];
        self.navigationItem.rightBarButtonItems = [NSArray arrayWithObjects:item1,item2,nil];
`
是不行的 
貌似直接在这个方法这样写也不对
`+(UIBarButtonItem *)itemWithTarget:(id)target
                            action:(SEL)action
                        nomalImage:(UIImage *)nomalImage
                  higeLightedImage:(UIImage *)higeLightedImage
                   imageEdgeInsets:(UIEdgeInsets)imageEdgeInsets {
    
    UIButton *button = [UIButton buttonWithType:UIButtonTypeSystem];
    [button addTarget:target action:action forControlEvents:UIControlEventTouchUpInside];
    
    [button setImage:[nomalImage imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal] forState:UIControlStateNormal];
    if (higeLightedImage) {
        [button setImage:higeLightedImage forState:UIControlStateHighlighted];
    }
    [button sizeToFit];
    if (button.bounds.size.width < 40) {
        CGFloat width = 40 / button.bounds.size.height * button.bounds.size.width;
        button.bounds = CGRectMake(0, 0, width, 40);
    }
    
    button.imageEdgeInsets = imageEdgeInsets;
    UIButton *button1 = [UIButton buttonWithType:UIButtonTypeSystem];
    [button1 addTarget:target action:action forControlEvents:UIControlEventTouchUpInside];
    
    [button1 setImage:[nomalImage imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal] forState:UIControlStateNormal];
    if (higeLightedImage) {
        [button1 setImage:higeLightedImage forState:UIControlStateHighlighted];
    }
    [button1 sizeToFit];
    if (button1.bounds.size.width < 40) {
        CGFloat width = 40 / button1.bounds.size.height * button1.bounds.size.width;
        button1.bounds = CGRectMake(45, 0, width, 40);
    }
    button1.imageEdgeInsets = imageEdgeInsets;
    UIView *viewBtn = [[UIView alloc]initWithFrame:CGRectMake(0, 0, (button.frame.size.width + button1.frame.size.width +5), 40)];
    [viewBtn sizeToFit];
    [viewBtn addSubview:button];
    [viewBtn setUserInteractionEnabled:YES];
    [viewBtn addSubview:button1];
//    viewBtn.backgroundColor = [UIColor yellowColor];
    return [[UIBarButtonItem alloc] initWithCustomView:viewBtn];
    
}`

**Comment by spicyShrimp** [comment]
很多人问这个问题
我简单的写了方法,更新到了demo中,可以下载demo具体查看

//多个按钮可以使用自定义视图的方式,这里没有添加快捷方式,使用的是普通的创建方法
//如有需要,可自行根据需求添加快捷创建多个按钮的方法
UIView *barView = [[UIView alloc]initWithFrame:CGRectMake(0, 0, 80, 40)];

UIButton *btn1 = [UIButton buttonWithType:UIButtonTypeCustom];
btn1.frame = CGRectMake(0, 0, 40, 40);
 [btn1 setImage:[UIImage imageNamed:@"nav_add"] forState:UIControlStateNormal];
[btn1 addTarget:self action:@selector(pushAction) forControlEvents:UIControlEventTouchUpInside];
[barView addSubview:btn1];

UIButton *btn2 = [UIButton buttonWithType:UIButtonTypeCustom];
btn2.frame = CGRectMake(40, 0, 40, 40);
[btn2 setImage:[UIImage imageNamed:@"nav_add"] forState:UIControlStateNormal];
[btn2 addTarget:self action:@selector(pushAction) forControlEvents:UIControlEventTouchUpInside];
 [barView addSubview:btn2];
        
self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc]initWithCustomView:barView];

**Comment by JerryDJX** [comment]
好的 谢谢哈

在 2017-09-27 12:23:38，"Charles" <notifications@github.com> 写道：


很多人问这个问题
我简单的写了方法,更新到了demo中,可以下载demo具体查看

//多个按钮可以使用自定义视图的方式,这里没有添加快捷方式,使用的是普通的创建方法
//如有需要,可自行根据需求添加快捷创建多个按钮的方法
UIView *barView = [[UIView alloc]initWithFrame:CGRectMake(0, 0, 80, 40)];

UIButton *btn1 = [UIButton buttonWithType:UIButtonTypeCustom];
btn1.frame = CGRectMake(0, 0, 40, 40);
[btn1 setImage:[UIImage imageNamed:@"nav_add"] forState:UIControlStateNormal];
[btn1 addTarget:self action:@selector(pushAction) forControlEvents:UIControlEventTouchUpInside];
[barView addSubview:btn1];

UIButton *btn2 = [UIButton buttonWithType:UIButtonTypeCustom];
btn2.frame = CGRectMake(40, 0, 40, 40);
[btn2 setImage:[UIImage imageNamed:@"nav_add"] forState:UIControlStateNormal];
[btn2 addTarget:self action:@selector(pushAction) forControlEvents:UIControlEventTouchUpInside];
[barView addSubview:btn2];

self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc]initWithCustomView:barView];

**Comment by spicyShrimp** [comment]
如果问题解决请关闭issues

**Comment by YanPengImp** [comment]
这个问题是设置leftBarButtonItem的时候用自定义视图修改内部约束的时候remove右边约束导致的，其实设置rightBarButtonItems的时候是设置对了，只是视图在屏幕外去了。修改下那行代码就行了。

**Comment by spicyShrimp** [comment]
都可以的  方法你们都可以自行扩展,每一个项目的要求都不完全一样,我这只是个demo
