### ISSUE TITLE
不太行

### ISSUE THREAD

**Issue by RiberWang** [spicyShrimp/iOS-11-UINavigationItem-SXFixSpace#8]
好像不是太好用
只是修改了偏移位置，点击区域并不能兼容
不设置偏移位置，效果好像并没有什么用，还是距离边距很远

**Comment by spicyShrimp** [comment]
这个确定没有问题的，你看看是否没有引用正确？另外，还有新的解决方案链接，你可以参考

**Comment by RiberWang** [comment]
好了 item那个类别的方法用了没有什么作用

**Comment by spicyShrimp** [comment]
item那个类别 是方便使用customView创建item用的 这个demo中的方法就是通过修改customview的约束来修改偏移的,所以是有作用的  新的解决方案中的则是另一种方案  不依赖customView  那个方案中item的类别确实可以不需要,其兼容系统创建的各种方式

**Comment by spicyShrimp** [comment]
你如果使用的这个方案  请参考demo中的写法  其有一定的局限性  所以写法不能太随意

**Comment by RiberWang** [comment]
好的 谢谢指点
